updated file pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -51,17 +51,25 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-      - name: Build fat JAR with Maven
+      - name: Clean and Build fat JAR with Maven
         env:
           MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
-        run: mvn -B package --file pom.xml -DskipTests=true
+        run: |
+          mvn -B clean package --file pom.xml -DskipTests=true
+          # Store the built JAR as a pipeline artifact
+      - name: Check if JAR file was built successfully
+        run: |
+          if [ ! -f "target/*.jar" ]; then
+            echo "Error: JAR file was not found."
+            exit 1
+          fi
       - name: Archive artifacts
         uses: actions/upload-artifact@v4
         with:
           name: Book-Library-Artifact
           path: target/*.jar
 
-  publish:
+  publish-docker-image:
     runs-on: ubuntu-latest
     needs: build
     steps:
@@ -77,24 +85,6 @@ jobs:
         with:
           name: Book-Library-Artifact
           path: target/
-      # Proceed with publish steps
-      - name: Verify with Maven
-        env:
-          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
-        run: mvn --batch-mode --update-snapshots verify -DskipTests=true
-      - name: Create staging directory and copy artifact
-        run: mkdir staging && cp target/*.jar staging
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: Book-Library-Artifact-${{ github.run_id }}
-          path: staging
-  publish-docker-image:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Check out the repository
-        uses: actions/checkout@v4
 
       # Set up Docker Buildx
       - name: Set up Docker Buildx
